# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: leoherna <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/18 10:05:00 by leoherna          #+#    #+#              #
#    Updated: 2024/10/18 10:05:00 by leoherna         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


NAME = span

CC = c++

CFLAGS = -g -Wall -Wextra -Werror -I includes -std=c++98


HEADER = Span

TEMPLATE = 

SRCS = Span main

INCLUDES = $(addsuffix .hpp, $(addprefix includes/, $(HEADER))) $(addsuffix .tpp, $(addprefix includes/, $(TEMPLATE)))

SRC = $(addsuffix .cpp, $(addprefix srcs/, $(SRCS)))

OBJ = $(SRC:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJ)
				@echo "\033[0;32m$(NAME) Compilé !"
				@$(CC) $(CFLAGS) -o $(NAME) $(OBJ) -I.
				@echo "\n\033[0m./$(NAME) pour exécuter le programme !"

%.o: %.cpp $(INCLUDES)
				@printf "\033[0;33mGénération des objets $(NAME)... %-33.33s\r\n" $@
				@$(CC) $(CFLAGS) -c $< -o $@

debug:
				@echo "INCLUDES: $(INCLUDES)"
				@echo "SRC: $(SRC)"
				@echo "OBJ: $(OBJ)"


clean:
				@echo "\nSuppression des binaires..."
				@rm -f $(OBJ)
				@echo "\033[0m"

fclean: clean
				@echo "\nSuppression de l'exécutable..."
				@rm -f $(NAME)
				@echo "\033[0m"

re: fclean all

.PHONY: all clean fclean re
